# Generated by Django 4.1.1 on 2023-10-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_follow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name",)},
        ),
    ]
