# Generated by Django 4.1.1 on 2023-10-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_alter_follow_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="date_created",
            new_name="date",
        ),
    ]
